import Head from 'next/head';
import { useEffect } from 'react';
import HomeBanner from '../components/Home';
import Aboutme from '../components/Aboutme';
import Technology from '../components/Technology';
import Projects from '../components/Projects';
import Contact from '../components/Contact';
import Footer from '../components/Footer';
export default function Home() {
	// useEffect(() => {
	// 	console.log(document.getElementsByTagName('canvas'));
	// 	const canvas = Array.from(document.getElementsByTagName('canvas'));
	// 	console.log([...canvas]);
	// 	console.log(window);
	// 	const mycanvas = [...canvas][0];
	// 	if (mycanvas) {
	// 		console.log(mycanvas);
	// 		mycanvas.style.width = window.innerWidth;
	// 		mycanvas.style.overflowX = 'hidden';
	// 	}
	// }, []);

	return (
		<>
			<Head>
				<title>zinpainghtet.developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HomeBanner />
			<Aboutme />
			<Technology />
			<Projects />
			<Contact />
			<Footer />
		</>
	);
}
