import Head from 'next/head';
import { useEffect } from 'react';
import HomeBanner from '../components/Home';
import Aboutme from '../components/Aboutme';
import Technology from '../components/Technology';
import Projects from '../components/Projects';
import Contact from '../components/Contact';
import Footer from '../components/Footer';



export default function Home(props) {
	// console.log(props.skills.data[0].attributes.image);
	return (
		<>
			<Head>
				<title>zinpainghtet.developer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HomeBanner />
			<Aboutme />
			<Technology />
			<Projects />
			<Contact />
			<Footer />
		</>
	);
}
